// Code generated by "stringer -type=Rank"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-0]
	_ = x[Two-1]
	_ = x[Three-2]
	_ = x[Four-3]
	_ = x[Five-4]
	_ = x[Six-5]
	_ = x[Eight-6]
	_ = x[Nine-7]
	_ = x[Ten-8]
	_ = x[Jack-9]
	_ = x[Queen-10]
	_ = x[King-11]
}

const _Rank_name = "AceTwoThreeFourFiveSixEightNineTenJackQueenKing"

var _Rank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 31, 34, 38, 43, 47}

func (i Rank) String() string {
	if i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
